FROM alpine:3.21
RUN apk add --no-cache ca-certificates

ARG TARGETARCH

COPY docker-bins/linux-${TARGETARCH}/serverbee-server /usr/local/bin/

VOLUME /data
ENV SERVERBEE_SERVER__DATA_DIR=/data
EXPOSE 9527

CMD ["serverbee-server"]
