/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangDocsDotmdxRouteImport } from './routes/$lang/docs[.]mdx'
import { Route as LangLlmsFullDottxtRouteImport } from './routes/$lang/llms-full[.]txt'
import { Route as LangLlmsDottxtRouteImport } from './routes/$lang/llms[.]txt'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'
import { Route as LangDocsChar123Char125DotmdxRouteImport } from './routes/$lang/docs/{$}[.]mdx'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsDotmdxRoute = LangDocsDotmdxRouteImport.update({
  id: '/docs.mdx',
  path: '/docs.mdx',
  getParentRoute: () => LangRoute,
} as any)
const LangLlmsFullDottxtRoute = LangLlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => LangRoute,
} as any)
const LangLlmsDottxtRoute = LangLlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => LangRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsChar123Char125DotmdxRoute =
  LangDocsChar123Char125DotmdxRouteImport.update({
    id: '/docs/{$}.mdx',
    path: '/docs/{$}.mdx',
    getParentRoute: () => LangRoute,
  } as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/docs.mdx': typeof LangDocsDotmdxRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.mdx': typeof LangDocsChar123Char125DotmdxRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/docs.mdx': typeof LangDocsDotmdxRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.mdx': typeof LangDocsChar123Char125DotmdxRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/docs.mdx': typeof LangDocsDotmdxRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.mdx': typeof LangDocsChar123Char125DotmdxRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$lang/docs.mdx'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.mdx'
    | '/llms.mdx/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$lang/docs.mdx'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.mdx'
    | '/llms.mdx/docs/$'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$lang/docs.mdx'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.mdx'
    | '/llms.mdx/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs.mdx': {
      id: '/$lang/docs.mdx'
      path: '/docs.mdx'
      fullPath: '/$lang/docs.mdx'
      preLoaderRoute: typeof LangDocsDotmdxRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/llms-full.txt': {
      id: '/$lang/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/$lang/llms-full.txt'
      preLoaderRoute: typeof LangLlmsFullDottxtRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/llms.txt': {
      id: '/$lang/llms.txt'
      path: '/llms.txt'
      fullPath: '/$lang/llms.txt'
      preLoaderRoute: typeof LangLlmsDottxtRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs/{$}.mdx': {
      id: '/$lang/docs/{$}.mdx'
      path: '/docs/{$}.mdx'
      fullPath: '/$lang/docs/{$}.mdx'
      preLoaderRoute: typeof LangDocsChar123Char125DotmdxRouteImport
      parentRoute: typeof LangRoute
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteChildren {
  LangDocsDotmdxRoute: typeof LangDocsDotmdxRoute
  LangLlmsFullDottxtRoute: typeof LangLlmsFullDottxtRoute
  LangLlmsDottxtRoute: typeof LangLlmsDottxtRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangDocsChar123Char125DotmdxRoute: typeof LangDocsChar123Char125DotmdxRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangDocsDotmdxRoute: LangDocsDotmdxRoute,
  LangLlmsFullDottxtRoute: LangLlmsFullDottxtRoute,
  LangLlmsDottxtRoute: LangLlmsDottxtRoute,
  LangIndexRoute: LangIndexRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangDocsChar123Char125DotmdxRoute: LangDocsChar123Char125DotmdxRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
