/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/agent/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/alert-rules': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_rules']
    put?: never
    post: operations['create_rule']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/alert-rules/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_rule']
    put: operations['update_rule']
    post?: never
    delete: operations['delete_rule']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/audit-logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_audit_logs']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/2fa/disable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['totp_disable']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/2fa/enable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['totp_enable']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/2fa/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['totp_setup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/2fa/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['totp_status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/api-keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_api_keys']
    put?: never
    post: operations['create_api_key']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/api-keys/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['delete_api_key']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oauth/{provider}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Redirect user to the OAuth provider's authorization page. */
    get: operations['oauth_authorize']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oauth/{provider}/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Handle the OAuth callback from the provider. */
    get: operations['oauth_callback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oauth/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_oauth_accounts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oauth/accounts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['unlink_oauth_account']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/oauth/providers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List configured OAuth providers. */
    get: operations['list_providers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['change_password']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/notification-groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_notification_groups']
    put?: never
    post: operations['create_notification_group']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/notification-groups/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_group']
    put: operations['update_notification_group']
    post?: never
    delete: operations['delete_notification_group']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/notifications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_notifications']
    put?: never
    post: operations['create_notification']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/notifications/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_notification']
    put: operations['update_notification']
    post?: never
    delete: operations['delete_notification']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/notifications/{id}/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['test_notification']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/ping-tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_tasks']
    put?: never
    post: operations['create_ping_task']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/ping-tasks/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_ping_task']
    put: operations['update_task']
    post?: never
    delete: operations['delete_task']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/ping-tasks/{id}/records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_ping_records']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/server-groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_server_groups']
    put?: never
    post: operations['create_server_group']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/server-groups/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['update_server_group']
    post?: never
    delete: operations['delete_server_group']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_servers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_server']
    put: operations['update_server']
    post?: never
    delete: operations['delete_server']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{id}/gpu-records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_gpu_records']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{id}/records': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_server_records']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/{id}/upgrade': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['trigger_upgrade']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/servers/batch-delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['batch_delete']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_settings']
    put: operations['update_settings']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/settings/auto-discovery-key': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_auto_discovery_key']
    put: operations['regenerate_auto_discovery_key']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/settings/backup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Download a backup of the SQLite database. */
    post: operations['create_backup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/settings/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore the database from an uploaded backup file.
     *     The server should be restarted after restore.
     *     Note: request body is raw binary (application/octet-stream).
     */
    post: operations['restore_backup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['public_status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['create_task']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tasks/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_task']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tasks/{id}/results': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_task_results']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_users']
    put?: never
    post: operations['create_user']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['get_user']
    put: operations['update_user']
    post?: never
    delete: operations['delete_user']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  headers: never
  parameters: never
  pathItems: never
  requestBodies: never
  responses: never
  schemas: {
    AlertRule: {
      cover_type: string
      /** Format: date-time */
      created_at: string
      enabled: boolean
      fail_trigger_tasks?: string | null
      id: string
      name: string
      notification_group_id?: string | null
      recover_trigger_tasks?: string | null
      rules_json: string
      server_ids_json?: string | null
      trigger_mode: string
      /** Format: date-time */
      updated_at: string
    }
    AlertRuleItem: {
      cycle_interval?: string | null
      /** Format: int64 */
      cycle_limit?: number | null
      /** Format: int32 */
      duration?: number | null
      /** Format: double */
      max?: number | null
      /** Format: double */
      min?: number | null
      rule_type: string
    }
    ApiKeyResponse: {
      created_at: string
      id: string
      key?: string | null
      key_prefix: string
      name: string
    }
    AuditListResponse: {
      entries: components['schemas']['AuditLogEntry'][]
      /** Format: int64 */
      total: number
    }
    AuditLogEntry: {
      action: string
      created_at: string
      detail?: string | null
      /** Format: int64 */
      id: number
      ip: string
      user_id: string
    }
    AutoDiscoveryKeyResponse: {
      key: string
    }
    BatchDeleteRequest: {
      ids: string[]
    }
    BatchDeleteResponse: {
      /** Format: int64 */
      deleted: number
    }
    ChangePasswordRequest: {
      new_password: string
      old_password: string
    }
    CreateAlertRule: {
      cover_type?: string
      enabled?: boolean
      name: string
      notification_group_id?: string | null
      rules: components['schemas']['AlertRuleItem'][]
      server_ids?: string[] | null
      trigger_mode?: string
    }
    CreateApiKeyRequest: {
      name: string
    }
    CreateGroupRequest: {
      name: string
    }
    CreateNotification: {
      config_json: unknown
      enabled?: boolean
      name: string
      notify_type: string
    }
    CreateNotificationGroup: {
      name: string
      notification_ids: string[]
    }
    CreatePingTask: {
      enabled?: boolean
      /** Format: int32 */
      interval?: number
      name: string
      probe_type: string
      server_ids?: string[]
      target: string
    }
    CreateTaskRequest: {
      command: string
      server_ids: string[]
      /** Format: int32 */
      timeout?: number | null
    }
    CreateUserInput: {
      password: string
      role?: string
      username: string
    }
    ErrorBody: {
      error: components['schemas']['ErrorDetail']
    }
    ErrorDetail: {
      code: string
      message: string
    }
    GpuRecord: {
      /** Format: int32 */
      device_index: number
      device_name: string
      /** Format: int64 */
      id: number
      /** Format: int64 */
      mem_total: number
      /** Format: int64 */
      mem_used: number
      server_id: string
      /** Format: double */
      temperature: number
      /** Format: date-time */
      time: string
      /** Format: double */
      utilization: number
    }
    LoginRequest: {
      password: string
      totp_code?: string | null
      username: string
    }
    LoginResponse: {
      must_change_password: boolean
      role: string
      user_id: string
      username: string
    }
    MeResponse: {
      must_change_password: boolean
      role: string
      user_id: string
      username: string
    }
    Notification: {
      config_json: string
      /** Format: date-time */
      created_at: string
      enabled: boolean
      id: string
      name: string
      notify_type: string
    }
    NotificationGroup: {
      /** Format: date-time */
      created_at: string
      id: string
      name: string
      notification_ids_json: string
    }
    OAuthAccount: {
      /** Format: date-time */
      created_at: string
      display_name?: string | null
      email?: string | null
      id: string
      provider: string
      provider_user_id: string
      user_id: string
    }
    OAuthProvidersResponse: {
      providers: string[]
    }
    PingRecord: {
      error?: string | null
      /** Format: int64 */
      id: number
      /** Format: double */
      latency: number
      server_id: string
      success: boolean
      task_id: string
      /** Format: date-time */
      time: string
    }
    PingTask: {
      /** Format: date-time */
      created_at: string
      enabled: boolean
      id: string
      /** Format: int32 */
      interval: number
      name: string
      probe_type: string
      server_ids_json: string
      target: string
    }
    RegisterResponse: {
      server_id: string
      token: string
    }
    ServerGroup: {
      /** Format: date-time */
      created_at: string
      id: string
      name: string
      /** Format: int32 */
      weight: number
    }
    /** @description Server response DTO — excludes sensitive fields (token_hash, token_prefix). */
    ServerResponse: {
      agent_version?: string | null
      billing_cycle?: string | null
      country_code?: string | null
      cpu_arch?: string | null
      /** Format: int32 */
      cpu_cores?: number | null
      cpu_name?: string | null
      /** Format: date-time */
      created_at: string
      currency?: string | null
      /** Format: int64 */
      disk_total?: number | null
      /** Format: date-time */
      expired_at?: string | null
      group_id?: string | null
      hidden: boolean
      id: string
      ipv4?: string | null
      ipv6?: string | null
      kernel_version?: string | null
      /** Format: int64 */
      mem_total?: number | null
      name: string
      os?: string | null
      /** Format: double */
      price?: number | null
      public_remark?: string | null
      region?: string | null
      remark?: string | null
      /** Format: int64 */
      swap_total?: number | null
      /** Format: int64 */
      traffic_limit?: number | null
      traffic_limit_type?: string | null
      /** Format: date-time */
      updated_at: string
      virtualization?: string | null
      /** Format: int32 */
      weight: number
    }
    StatusGroup: {
      id: string
      name: string
    }
    StatusMetrics: {
      /** Format: double */
      cpu: number
      /** Format: int64 */
      disk_total: number
      /** Format: int64 */
      disk_used: number
      /** Format: double */
      load1: number
      /** Format: int64 */
      mem_total: number
      /** Format: int64 */
      mem_used: number
      /** Format: int64 */
      net_in_speed: number
      /** Format: int64 */
      net_in_transfer: number
      /** Format: int64 */
      net_out_speed: number
      /** Format: int64 */
      net_out_transfer: number
      /** Format: int64 */
      uptime: number
    }
    StatusPageResponse: {
      groups: components['schemas']['StatusGroup'][]
      online_count: number
      servers: components['schemas']['StatusServer'][]
      total_count: number
    }
    /** @description Public status info for a single server. */
    StatusServer: {
      country_code?: string | null
      group_id?: string | null
      id: string
      metrics?: null | components['schemas']['StatusMetrics']
      name: string
      online: boolean
      os?: string | null
      public_remark?: string | null
      region?: string | null
    }
    SystemSettings: {
      custom_css?: string | null
      custom_js?: string | null
      site_description?: string | null
      site_name?: string | null
    }
    TaskResponse: {
      command: string
      /** Format: date-time */
      created_at: string
      id: string
      server_ids: string[]
    }
    TaskResult: {
      /** Format: int32 */
      exit_code: number
      /** Format: date-time */
      finished_at: string
      /** Format: int64 */
      id: number
      output: string
      server_id: string
      task_id: string
    }
    TotpDisableRequest: {
      password: string
    }
    TotpSetupResponse: {
      otpauth_url: string
      qr_code_base64: string
      secret: string
    }
    TotpStatusResponse: {
      enabled: boolean
    }
    TotpVerifyRequest: {
      code: string
    }
    UpdateAlertRule: {
      cover_type?: string | null
      enabled?: boolean | null
      name?: string | null
      notification_group_id?: string | null
      rules?: components['schemas']['AlertRuleItem'][] | null
      server_ids?: string[] | null
      trigger_mode?: string | null
    }
    UpdateGroupRequest: {
      name?: string | null
      /** Format: int32 */
      weight?: number | null
    }
    UpdateNotification: {
      config_json?: unknown
      enabled?: boolean | null
      name?: string | null
      notify_type?: string | null
    }
    UpdateNotificationGroup: {
      name?: string | null
      notification_ids?: string[] | null
    }
    UpdatePingTask: {
      enabled?: boolean | null
      /** Format: int32 */
      interval?: number | null
      name?: string | null
      probe_type?: string | null
      server_ids?: string[] | null
      target?: string | null
    }
    UpdateServerInput: {
      billing_cycle?: string | null
      currency?: string | null
      /** Format: date-time */
      expired_at?: string | null
      group_id?: string | null
      hidden?: boolean | null
      name?: string | null
      /** Format: double */
      price?: number | null
      public_remark?: string | null
      remark?: string | null
      /** Format: int64 */
      traffic_limit?: number | null
      traffic_limit_type?: string | null
      /** Format: int32 */
      weight?: number | null
    }
    UpdateUserInput: {
      password?: string | null
      role?: string | null
    }
    UpgradeRequest: {
      /** @description URL to download the new agent binary from */
      download_url: string
      /** @description Target version string (e.g. "0.2.0") */
      version: string
    }
    UserResponse: {
      /** Format: date-time */
      created_at: string
      has_2fa: boolean
      id: string
      role: string
      /** Format: date-time */
      updated_at: string
      username: string
    }
  }
}
export type $defs = Record<string, never>
export interface operations {
  batch_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchDeleteRequest']
      }
    }
    responses: {
      /** @description Batch delete result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchDeleteResponse']
        }
      }
    }
  }
  change_password: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description Password changed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_api_key: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApiKeyRequest']
      }
    }
    responses: {
      /** @description API key created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse']
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_backup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Database backup file (SQLite) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_notification: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNotification']
      }
    }
    responses: {
      /** @description Notification created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Notification']
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_notification_group: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNotificationGroup']
      }
    }
    responses: {
      /** @description Notification group created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationGroup']
        }
      }
    }
  }
  create_ping_task: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePingTask']
      }
    }
    responses: {
      /** @description Ping task created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PingTask']
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_rule: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAlertRule']
      }
    }
    responses: {
      /** @description Alert rule created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRule']
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_server_group: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGroupRequest']
      }
    }
    responses: {
      /** @description Group created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerGroup']
        }
      }
      /** @description Group name already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_task: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTaskRequest']
      }
    }
    responses: {
      /** @description Task created and dispatched */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskResponse']
        }
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserInput']
      }
    }
    responses: {
      /** @description User created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Username already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_api_key: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description API key ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description API key deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description API key not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_notification: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Notification deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_notification_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification group ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Notification group deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_rule: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Alert rule ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Alert rule deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_server: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Server deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Server not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_server_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server group ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_task: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Ping task ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ping task deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Cannot delete last admin */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_auto_discovery_key: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Auto-discovery key */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AutoDiscoveryKeyResponse']
        }
      }
    }
  }
  get_gpu_records: {
    parameters: {
      query: {
        from: string
        to: string
      }
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description GPU metric records */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GpuRecord'][]
        }
      }
    }
  }
  get_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification group ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Notification group details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationGroup']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_notification: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Notification details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Notification']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_ping_records: {
    parameters: {
      query: {
        from: string
        to: string
        server_id?: string | null
      }
      header?: never
      path: {
        /** @description Ping task ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ping records */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PingRecord'][]
        }
      }
    }
  }
  get_ping_task: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Ping task ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ping task details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PingTask']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_rule: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Alert rule ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Alert rule details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRule']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_server: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Server details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerResponse']
        }
      }
      /** @description Server not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_server_records: {
    parameters: {
      query: {
        from: string
        to: string
        interval?: string
      }
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Server metric records */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_settings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description System settings */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemSettings']
        }
      }
    }
  }
  get_task: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Task ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Task details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskResponse']
        }
      }
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_task_results: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Task ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Task results */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskResult'][]
        }
      }
    }
  }
  get_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_api_keys: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of API keys */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiKeyResponse'][]
        }
      }
    }
  }
  list_audit_logs: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Audit log entries */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditListResponse']
        }
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_notification_groups: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all notification groups */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationGroup'][]
        }
      }
    }
  }
  list_notifications: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all notifications */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Notification'][]
        }
      }
    }
  }
  list_oauth_accounts: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List linked OAuth accounts */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OAuthAccount'][]
        }
      }
    }
  }
  list_providers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of configured OAuth providers */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OAuthProvidersResponse']
        }
      }
    }
  }
  list_rules: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all alert rules */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRule'][]
        }
      }
    }
  }
  list_server_groups: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all server groups */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerGroup'][]
        }
      }
    }
  }
  list_servers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all servers */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerResponse'][]
        }
      }
    }
  }
  list_tasks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all ping tasks */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PingTask'][]
        }
      }
    }
  }
  list_users: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List all users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse'][]
        }
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description 2FA code required (code: 2fa_required) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current user info */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  oauth_authorize: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description OAuth provider (github, google) */
        provider: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to provider */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Provider not configured */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  oauth_callback: {
    parameters: {
      query: {
        /** @description Authorization code */
        code: string
        /** @description CSRF state token */
        state: string
      }
      header?: never
      path: {
        /** @description OAuth provider */
        provider: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redirect to frontend after login */
      302: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid callback */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  public_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Public server status page data */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusPageResponse']
        }
      }
    }
  }
  regenerate_auto_discovery_key: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Key regenerated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AutoDiscoveryKeyResponse']
        }
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Agent registered */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RegisterResponse']
        }
      }
      /** @description Auto-discovery key not configured */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid auto-discovery key */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  restore_backup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description SQLite backup file */
    requestBody: {
      content: {
        'application/octet-stream': string
      }
    }
    responses: {
      /** @description Database restored, restart required */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid backup file */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  test_notification: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Test notification sent */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  totp_disable: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpDisableRequest']
      }
    }
    responses: {
      /** @description 2FA disabled */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid password */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  totp_enable: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpVerifyRequest']
      }
    }
    responses: {
      /** @description 2FA enabled */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid TOTP code */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  totp_setup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description TOTP setup data */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TotpSetupResponse']
        }
      }
    }
  }
  totp_status: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 2FA status */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TotpStatusResponse']
        }
      }
    }
  }
  trigger_upgrade: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpgradeRequest']
      }
    }
    responses: {
      /** @description Upgrade command sent to agent */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Server not found or not online */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  unlink_oauth_account: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description OAuth account ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OAuth account unlinked */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_notification: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNotification']
      }
    }
    responses: {
      /** @description Notification updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Notification']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_notification_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Notification group ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNotificationGroup']
      }
    }
    responses: {
      /** @description Notification group updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationGroup']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_rule: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Alert rule ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAlertRule']
      }
    }
    responses: {
      /** @description Alert rule updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRule']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_server: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateServerInput']
      }
    }
    responses: {
      /** @description Server updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerResponse']
        }
      }
      /** @description Server not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_server_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Server group ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateGroupRequest']
      }
    }
    responses: {
      /** @description Group updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServerGroup']
        }
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_settings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SystemSettings']
      }
    }
    responses: {
      /** @description Settings updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemSettings']
        }
      }
    }
  }
  update_task: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Ping task ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePingTask']
      }
    }
    responses: {
      /** @description Ping task updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PingTask']
        }
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  update_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserInput']
      }
    }
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserResponse']
        }
      }
      /** @description Forbidden — admin only */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
